language: ruby
cache: bundler
git:
  submodules: false
notifications:
  email:
    recipients:
      - gabrielfalcone@gmail.com
    on_success: always
    on_failure: always
rvm:
  - "2.0.0"

env:
  - RAILS_ENV=production

before_script:

script:
  - bundle exec rake db:migrate

after_success:
